### ISSUE TITLE
Ships not engaging with space amoeba

### ISSUE THREAD

**Issue by sheepo99** [KilgoreTroutMaskReplicant/1oom#10]
Using git commit 6c45828

*EDIT* the same problem happens with Space Crystal

Issue: if a space amoeba is parked on a planet, moving ships towards it does not engage it in combat. Contrarily, if a ship is already parked on a planet and the amoeba moves into it, combat will engage regularly. I'm not entirely sure how it is in the original game, but this seems inconsistent to.

How to replicate:
1 - Load save 5 named "undo".
2 - there is an amoeba moving in the direction of Ursa. Let it destroy the planet.
3 - the amoeba will stay parked in the planet after destroying the Bulrathi colony.
4 - Immediately send the big fleet parked in Ssla against the amoeba. it should arrive there in two turns.
5 - place other scout or light ships in the vicinity planets.
6 - when the big fleet reaches Ursa, you will notice combat will not engage when the amoeba is there.
7 - as soon as the amoeba moves to another system with one of your ships already parked there, combat will engage as normal.

[space amoeba bug.zip](https://github.com/KilgoreTroutMaskReplicant/1oom/files/1978105/space.amoeba.bug.zip)

**Comment by KilgoreTroutMaskReplicant** [comment]
The behaviour matches the original MOO1 v1.3. This is what happens:
1 - The monster arrives to the destination (monster (x,y) match dest planet (x,y))
2 - Battle happens if the monster (x, y) matches the dest (x, y) and any fleets / missile bases exist
3 - The monster selects a new destination starts waiting for 4 turns before departing

No more battles since the (x,y) coords do not match anymore. I do not know if this is a bug or a feature. Hence I added a toggle for it (monster_rest_att). Throw the following to some.txt:

0,"Attack resting monsters"
1,"Attack resting monsters!\nNo more hiding crystals or amoeba."
4,monster_rest_att,0,1

Then: 1oom_pbxmake some.txt babys_first_mod.pbx
And: 1oom_classic_sdl1 -file babys_first_mod.pbx

(Also fixed a related bug: "EMPIRE killed MONSTER" news were missing.)
